[package]
name = "brewer_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
log = "0.4.22"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
jammdb = "0.11.0"
derive_builder = "0.20.0"
reqwest = { version = "0.12.4", features = ["blocking"] }

